// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {files} from '../models';

export function ClearIndex():Promise<void>;

export function CompleteOnboarding(arg1:string):Promise<void>;

export function Execute(arg1:string):Promise<string>;

export function ExecuteContextAction(arg1:string,arg2:string):Promise<string>;

export function GetContextActions(arg1:string):Promise<Array<main.ContextAction>>;

export function GetIcon(arg1:string):Promise<string>;

export function GetIndexStatus():Promise<files.IndexStatus>;

export function HideWindow():Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function RefreshApps():Promise<void>;

export function ReindexFiles():Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchResult>>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
