// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearIndex() {
  return window['go']['main']['App']['ClearIndex']();
}

export function CompleteOnboarding(arg1) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function ExecuteContextAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteContextAction'](arg1, arg2);
}

export function GetContextActions(arg1) {
  return window['go']['main']['App']['GetContextActions'](arg1);
}

export function GetIcon(arg1) {
  return window['go']['main']['App']['GetIcon'](arg1);
}

export function GetIndexStatus() {
  return window['go']['main']['App']['GetIndexStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}

export function ReindexFiles() {
  return window['go']['main']['App']['ReindexFiles']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
